### ISSUE TITLE
Remove package search json

### ISSUE THREAD

**Issue by SomethingGeneric** [crystalux-project/amethyst#3]
Stale files left in `~/.cache/amethyst` after using search function

**Comment by axtloss** [comment]
I made this on purpose(and I also told you lol) to improve the speed incase the same thing is searched again

**Comment by SomethingGeneric** [comment]
Ope, my bad, you did tell me.

Maybe we should keep them (or the package repos) in a different place so that AME can easily have a "list installed AUR packages" function.

Now that I'm thinking it through, the repos of installed packages aren't really cached at all.

Maybe move cloned AUR repos to `~/.local/amethyst/packages` or something? And keep the JSON results in `~/.cache/amethyst`? That way you can implement a "list AUR" by just running `os.listdir()` on it.

**Comment by axtloss** [comment]
Implemented, will add an extra command to the amethyst.install in the packages repo to move the already cached packages to the new directory
