### ISSUE TITLE
Disable update prompt on iso

### ISSUE THREAD

**Issue by SomethingGeneric** [crystalux-project/amethyst#4]
Update prompt on iso makes people think they should reboot, which will ofc discard the update

**Comment by SomethingGeneric** [comment]
Just thought of a solution for this one. I've been creating a file, `/etc/buildstamp` iirc in the live ISO. If that exists, disable the reboot prompt

**Comment by axtloss** [comment]
Will add it later

**Comment by axtloss** [comment]
Added, view newest commit
