### ISSUE TITLE
Add option to list installed AUR pkgs

### ISSUE THREAD

**Issue by SomethingGeneric** [crystalux-project/amethyst#5]

**Comment by SomethingGeneric** [comment]
In the same vein, it seems like AME is only aware of one AUR package>

**Comment by axtloss** [comment]
What exactly do you mean?

**Comment by SomethingGeneric** [comment]
When I run `ame upg` it only shows the first AUR pkg I installed, not the second.

**Comment by axtloss** [comment]
what are the contents of ~/.cache/amethyst/packages and ~/.cache/amethyst

**Comment by SomethingGeneric** [comment]
![image](https://user-images.githubusercontent.com/12242178/118316649-15122600-b4c5-11eb-974f-20dd23773030.png)

**Comment by axtloss** [comment]
Are you on the newest amethyst version?

**Comment by axtloss** [comment]
Nevermind, just checked also have that issue, I'll look into it

**Comment by axtloss** [comment]
@SomethingGeneric fixed the issue, update ame and it should work again
